CONFIG_FILE = "openerp.yml"
LOCAL_CONFIG_TEMPLATE = "./etc/%s"
SAMPLE_CONFIG = LOCAL_CONFIG_TEMPLATE % "openerp-sample.yml"
CONFIG_TEMPLATE = LOCAL_CONFIG_TEMPLATE % CONFIG_FILE
CONFIG_DIR = "~/.pyopenerp"
DEFAULT_CONFIG = "%s/%s" % (CONFIG_DIR, CONFIG_FILE)
